=== malamalca/pures3/schemas/Pures/coneSchema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "array",
    "items" : {
        "type" : "object",
        "_additionalProperties": false,
        "required": ["id", "naziv", "klasifikacija", "prezracevanje"],
        "properties" : {
            "id": {"type": "string", "description": "Šifra cone"},
            "naziv": {"type": "string", "description": "Naziv cone"},
            "klasifikacija" : {
                "enum": ["St-1", "St-2", "St-3", "Go-1", "Ho-1", "Po-1", "In-1", "Sd-1", "Ra-1", "Kn-1", "Iz-1", "Iz-2", "Bo-1", "Sp-1"],
                "description": "Klasifikacija cone po standardu SIST ISO 18523-1"
            },

            "brutoProstornina": {"oneOf": [{"type": "number"}, {"type": "string"}], "description": "Šifra cone"},
            "netoProstornina": {"oneOf": [{"type": "number"}, {"type": "string"}], "description": "Prostornina zraka v kondicionirani coni v V [m³]"},
            "ogrevanaPovrsina": {"oneOf": [{"type": "number"}, {"type": "string"}], "description": "Kondicionirana površina cone A<sub>use</sub> [m²]"},
            "dolzina": {"oneOf": [{"type": "number"}, {"type": "string"}], "description": "Dolžina cone D [m]"},
            "sirina": {"oneOf": [{"type": "number"}, {"type": "string"}], "description": "Širina cone Š [m]"},
            "etaznaVisina": {"oneOf": [{"type": "number"}, {"type": "string"}], "description": "Etažna višina cone H [m]"},
            "steviloEtaz": {"type": "integer", "description": "Število etaž v coni n [-]"},

            "deltaPsi": {"type": "number", "description": "Dodatek spec. koeficientu transmisijskih toplotnih izgub zaradi toplotnih mostov ΔΨ<sub>tb</sub> [W/(m²K)]"},

            "notranjaTOgrevanje": {"type": "number", "description": "Notranja operativna temperatura v času ogrevanja θ<sub>op</sub> [°C]"},
            "notranjaTHlajenje": {"type": "number", "description": "Notranja operativna temperatura v času hlajenja θ<sub>op</sub> [°C]"},

            "toplotnaKapaciteta": {
                "oneOf": [
                    {"type": "number"},
                    {"enum": ["zeloLahkeKonstrukcije", "lahkeKonstrukcije", "srednjeTezkeKonstrukcije", "tezkeKonstrukcije", "zeloTezkeKonstrukcije"]}
                ],
                "description": "Specifična toplotna kapaciteta na m2 uporabne površine C [J/m²K]"
            },

            "infiltracija": {
                "type": "object",
                "required": ["n50", "lega", "zavetrovanost"],
                "properties": {
                    "n50": {"type": "number", "description": "Stopnja tesnosti stavbe n<sub>50</sub> [h<sup>-1</sup>]"},
                    "lega": {
                        "oneOf": [
                            {"type": "integer", "minimum": 1, "maximum": 6},
                            {"enum": ["naPodezelju", "visokaStavbaVMestu", "naPodezeljuMedDrevesi", "obkrozenaStavbaVMestu", "stavbaVPredmestju", "povprecnaStavbaVMestu"]}
                        ],
                        "description": "Lega stavbe za izračun vpliva vetra. Celoštevilčna oblika je zaradi združljivosti za nazaj zaporedna številka vrste lege (1-6)."
                    },
                    "zavetrovanost": {
                        "oneOf": [
                            {"type": "integer", "minimum": 1, "maximum": 2},
                            {"enum": ["izpostavljenaEnaFasada", "izpostavljenihVecFasad"]}
                        ],
                        "description": "Število izpostavljenih površin/fasad. Celoštevilčna oblika je zaradi združljivosti za nazaj zaporedna številka (1-2)."
                    }
                }
            },

            "notranjiViri": {
                "type": "object",
                "required": ["ogrevanje", "hlajenje"],
                "properties": {
                    "ogrevanje": {"type": "number", "description": "Specifični senzibilni toplotni tok v času ogrevanja cone q<sub>s</sub> [W/m²]"},
                    "hlajenje": {"type": "number", "description": "Specifični senzibilni toplotni tok v času hlajenja cone q<sub>s</sub> [W/m²]"}
                }
            },

            "prezracevanje": {
                "type": "object",
                "anyOf": [
                    {
                        "type": "object",
                        "required": ["vrsta"],
                        "properties": {
                            "vrsta": {"const": "naravno", "description": "Vrsta prezračevanja (naravno/prisilno/rekuperacija)"},
                            "izmenjava": {
                                "oneOf": [
                                    {"type": "number"},
                                    {
                                        "type": "object",
                                        "properties": {
                                            "ogrevanje": {"type": "number", "description": "Število izmenjav zraka v času ogrevanja n [1/h]"},
                                            "hlajenje": {"type": "number", "description": "Število izmenjav zraka v času hlajenja n [1/h]"}
                                        }
                                    }
                                ]
                            },
                            "volumenDovedenegaZraka": {
                                "oneOf": [
                                    {"type": "number"},
                                    {
                                        "type": "object",
                                        "properties": {
                                            "ogrevanje": {"type": "number", "description": "Količina dovedenega zraka v času ogrevanja V [m³/h]"},
                                            "hlajenje": {"type": "number", "description": "Količina dovedenega zraka v času hlajenja V [m³/h]"}
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    {
                        "type": "object",
                        "required": ["vrsta"],
                        "oneOf": [
                            {"required": ["izmenjava"]},
                            {"required": ["volumenDovedenegaZraka"]}
                        ],
                        "properties": {
                            "vrsta": {"const": "mehansko", "description": "Vrsta prezračevanja (naravno/prisilno/rekuperacija)"},
                            "regulacija": {
                                "enum": ["brez", "senzorPrisotnosti", "senzorCO2", "senzorStevilaLjudi"],
                                "description": "Vrsta regulacije prezračevanja (brez/senzorPrisotnosti/senzorCO2/senzorStevilaLjudi)"
                            },
                            "izmenjava": {
                                "type": "object",
                                "properties": {
                                    "ogrevanje": {"type": "number", "description": "Število izmenjav zraka v času ogrevanja n [1/h]"},
                                    "hlajenje": {"type": "number", "description": "Število izmenjav zraka v času hlajenja n [1/h]"}
                                }
                            },
                            "volumenDovedenegaZraka": {
                                "type": "object",
                                "properties": {
                                    "ogrevanje": {"type": "number", "description": "Količina dovedenega zraka v času ogrevanja V [m³/h]"},
                                    "hlajenje": {"type": "number", "description": "Količina dovedenega zraka v času hlajenja V [m³/h]"}
                                }
                            }
                        }
                    },
                    {
                        "type": "object",
                        "required": ["vrsta", "izkoristek"],
                        "oneOf": [
                            {"required": ["izmenjava"]},
                            {"required": ["volumenDovedenegaZraka"]}
                        ],
                        "properties": {
                            "vrsta": {"const": "rekuperacija", "description": "Vrsta prezračevanja (naravno/prisilno/rekuperacija)"},
                            "izkoristek": {"type": "number", "description": "Referenčni izkoristek vračanja toplote prezračevalnega sistema z rekuperacijo η<sub>V</sub> [-]"},
                            "regulacija": {
                                "enum": ["brez", "senzorPrisotnosti", "senzorCO2", "senzorStevilaLjudi"],
                                "description": "Vrsta regulacije prezračevanja (brez/senzorPrisotnosti/senzorCO2/senzorStevilaLjudi)"
                            },
                            "izmenjava": {
                                "type": "object",
                                "properties": {
                                    "ogrevanje": {"type": "number"},
                                    "hlajenje": {"type": "number"}
                                }
                            },
                            "volumenDovedenegaZraka": {
                                "type": "object",
                                "properties": {
                                    "ogrevanje": {"type": "number"},
                                    "hlajenje": {"type": "number"}
                                }
                            }
                        }
                    }
                ]
            },

            "TSV": {
                "type": "object",
                "properties": {
                    "steviloOseb": {"type": "number", "description": "Število oseb/uporabnikov cone n<sub>os</sub> [-]"},
                    "dnevnaKolicina": {"type": "number", "description": "Dnevna količina tople sanitarne vode po osebi V<sub>W,os,d</sub> [lit/d]"},
                    "toplaVodaT": {"type": "number", "description": "Temperatura TSV na iztočnem mestu θ<sub>w,h</sub> °C."},
                    "hladnaVodaT": {"type": "number", "description": "Temperatura hladne vodovodne vode na vstopu v stavbo θ<sub>w,h</sub> °C."}
                }
            },

            "razsvetljava": {
                "type": "object",
                "required": ["faktorDnevneSvetlobe"],
                "properties": {
                    "faktorDnevneSvetlobe": {"type": "number", "description": "Faktor dnevne svetlobe FDS<sub>T</sub> [-]"},
                    "mocSvetilk": {"type": "number", "description": "Specifična električna moč svetil na enoto kondicionirane površine cone P'<sub>L,zn</sub> [W/m²]"},
                    "faktorZmanjsanjaSvetlobnegaToka": {"type": "number", "description": "Faktor zmanjšanja svetlobnega toka F<sub>C,zn</sub> [-]"},
                    "faktorPrisotnosti": {"type": "number", "description": "Faktor prisotnosti uporabnikov F<sub>O,zn</sub> [-]"},
                    "ucinkovitostViraSvetlobe": {"type": "number", "description": "Energijska učinkovitost vira svetlobe η<sub>L</sub> [lm/W]"},
                    "osvetlitevDelovnePovrsine": {"type": "number", "description": "Projektirana osvetlitev delovne površine E<sub>task</sub> [lx]"},
                    "faktorZmanjsaneOsvetlitveDelovnePovrsine": {"type": "number", "description": "Faktor zmanjšane osvetlitve delovne površine F<sub>CA</sub> [-]"},
                    "faktorVzdrzevanja": {"type": "number", "description": "Faktor vzdrževanja svetilk F<sub>MF</sub> [-]"},
                    "faktorNaravneOsvetlitve": {"type": "number", "description": "Faktor naravne osvetlitve cone F<sub>D,zn</sub> [-]"},
                    "letnoUrPodnevi": {"type": "number", "description": "Letno število ur delovanje električne razsvetljave v dnevnem času t<sub>D</sub> [-]"},
                    "letnoUrPonoci": {"type": "number", "description": "Letno število ur delovanje električne razsvetljave v nočnem času t<sub>D</sub> [-]"},
                    "varnostna": {
                        "type": "object",
                        "properties": {
                            "energijaZaPolnjenje": {"type": "number", "description": "Dovedena energija za polnjenje baterij varnostnih sijalk na m² uporabne površine W<sub>pe,zn,an</sub> [kWh/m²an]"},
                            "energijaZaDelovanje": {"type": "number", "description": "Dovedena energija za regulacijo delovanja varnostnih sijalk na m² uporabne površine W<sub>pe,zn,an</sub> [kWh/m²an]"}
                        }
                    }
                }
            },

            "ovoj": {
                "type": "object",
                "properties": {
                    "netransparentneKonstrukcije": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": ["povrsina"],
                            "properties": {
                                "idKonstrukcije": {"type": "string"},
                                "opis": {"type": "string"},
                                "povrsina": {
                                    "oneOf": [{"type": "number"}, {"type": "string"}]
                                },
                                "naklon": {"enum": [0, 15, 30, 45, 60, 75, 90]},
                                "orientacija": {"enum": ["S", "SV", "V", "JV", "J", "JZ", "Z", "SZ"]},
                                "obseg": {
                                    "oneOf": [{"type": "number"}, {"type": "string"}]
                                },
                                "debelinaStene": {"type": "number"},
                                "tla": {"enum": ["pesek", "glina", "kamen"]},
                                "dodatnaIzolacija": {
                                    "type": "object",
                                    "required": ["lambda", "tip"],
                                    "properties": {
                                        "lambda": {"type": "number", "min": 0.01},
                                        "tip": {"enum": ["vertikalna", "horizontalna"]},
                                        "debelina": {"type": "number"},
                                        "dolzina": {"type": "number"}
                                    }
                                }
                            }
                        }
                    },
                    "transparentneKonstrukcije": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": [],
                            "properties": {
                                "idKonstrukcije": {"type": "string"},
                                "opis": {"type": "string"},
                                "stevilo": {"type": "integer"},
                                "povrsina": {
                                    "oneOf": [{"type": "number"}, {"type": "string"}]
                                },
                                "naklon": {"enum": [0, 15, 30, 45, 60, 75, 90]},
                                "orientacija": {"enum": ["S", "SV", "V", "JV", "J", "JZ", "Z", "SZ"]},

                                "visinaStekla": {"oneOf": [{"type": "number"}, {"type": "string"}]},
                                "sirinaStekla": {"oneOf": [{"type": "number"}, {"type": "string"}]},
                                "delezOkvirja": {"oneOf": [{"type": "number"}, {"type": "string"}]},
                                "dolzinaOkvirja": {"oneOf": [{"type": "number"}, {"type": "string"}]},

                                "faktorSencil": {"type": "number"},

                                "stranskoSencenje": {
                                    "type": "object",
                                    "properties": {
                                        "zgorajDolzina": {"type": "number"},
                                        "zgorajRazdalja": {"type": "number"},
                                        "levoDolzina": {"type": "number"},
                                        "levoRazdalja": {"type": "number"},
                                        "desnoDolzina": {"type": "number"},
                                        "desnoRazdalja": {"type": "number"}
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== malamalca/pures3/projects/Pures/TestniProjekt/podatki/cone.json
[
    {
        "id": "Cona1",
        "naziv": "Ogrevana cona",
        "klasifikacija": "St-1",
        "brutoProstornina": 672,
        "netoProstornina": 400,
        "ogrevanaPovrsina": 160,
        "dolzina": 10,
        "sirina": 8,
        "etaznaVisina": 3,
        "steviloEtaz": 3,

        "notranjaTOgrevanje": 20,
        "notranjaTHlajenje": 26,
        
        "infiltracija": {
            "n50": 0.6,
            "lega": "naPodezeljuMedDrevesi",
            "zavetrovanost": "izpostavljenihVecFasad"
        },

        "notranjiViri": {
            "ogrevanje": 4.1,
            "hlajenje": 4.1
        },

        "toplotnaKapaciteta": 165000,

        "TSV": {
            "toplaVodaT": 42,
            "hladnaVodaT": 10
        },

        "razsvetljava": {
            "faktorDnevneSvetlobe": 0.05,
            "mocSvetilk": 4
        },

        "prezracevanje": {
            "_vrsta": "mehansko",
            "_regulacija": "brez",
            "_volumenProjekt": 200,
            "_volumenDovedenegaZraka": {
                "ogrevanje": 200,
                "hlajenje": 200
            },

            "__vrsta": "naravno",
            "__izmenjava": {
                "ogrevanje": 0.5,
                "hlajenje": 0.5
            },

            "vrsta": "rekuperacija",
            "regulacija": "brez",
            "izkoristek": 0.9,
            "volumenProjekt": 200,
            "volumenDovedenegaZraka": {
                "ogrevanje": 200,
                "hlajenje": 200
            }
        },

        "deltaPsi": 0.04,
        "ovoj": {
            "netransparentneKonstrukcije": [
                {
                    "id": "K1",
                    "idKonstrukcije": "Z1",
                    "povrsina": 243,
                    "naklon": 90,
                    "orientacija": "S",
                    "barva": "svetla"
                },
                {
                    "id": "K2",
                    "idKonstrukcije": "Tp1",
                    "povrsina": 200,
                    "obseg": 40,
                    "debelinaStene": 0.46,
                    "tla": "pesek",
                    "dodatnaIzolacija": {
                        "lambda": 0.04,
                        "tip": "vertikalna",
                        "debelina": 0.2,
                        "dolzina": 0.5
                    }
                },
                {
                    "id": "K3",
                    "idKonstrukcije": "Ts1",
                    "povrsina": 200
                }
            ],
            "transparentneKonstrukcije": [
                {
                    "id": "V1",
                    "idKonstrukcije": "V1",
                    "povrsina": 3,
                    "naklon": 90,
                    "orientacija": "S",
                    "delezOkvirja": 1
                },
                {
                    "id": "O1",
                    "idKonstrukcije": "O1",
                    "povrsina": 15,
                    "naklon": 90,
                    "orientacija": "V",
                    
                    "visinaStekla": 2.3,
                    "sirinaStekla": 5.8,

                    "delezOkvirja": 0.1,
                    "dolzinaOkvirja": 16.2,

                    "faktorSencil": 0.05,

                    "stranskoSencenje": {
                        "zgorajDolzina": 0.2,
                        "zgorajRazdalja": 0.0,
                        "levoDolzina": 0.2,
                        "levoRazdalja": 0,
                        "desnoDolzina": 0.2,
                        "desnoRazdalja": 0
                    },

                    "sencenjeOvir": [
                        {
                            "kvadrant": 2,
                            "visinaNadTerenom": 1,
                            "visinaOvire": 20,
                            "oddaljenostOvire": 5
                        }
                    ]
                },
                {
                    "id": "O2",
                    "idKonstrukcije": "O1",
                    "stevilo": 3,

                    "povrsina": 5,
                    "naklon": 90,
                    "orientacija": "J",
                    
                    "visinaStekla": 2.3,
                    "sirinaStekla": 1.8,

                    "delezOkvirja": 0.17,
                    "dolzinaOkvirja": 8.2,

                    "faktorSencil": 0.3,

                    "stranskoSencenje": {
                        "zgorajDolzina": 0.2,
                        "zgorajRazdalja": 0,
                        "levoDolzina": 0.2,
                        "levoRazdalja": 0,
                        "desnoDolzina": 0.2,
                        "desnoRazdalja": 0
                    }
                },
                {
                    "id": "O3",
                    "idKonstrukcije": "O1",
                    "stevilo": 2,
                    
                    "povrsina": 1,
                    "naklon": 90,
                    "orientacija": "V",
                    
                    "visinaStekla": 0.9,
                    "sirinaStekla": 0.9,

                    "delezOkvirja": 0.19,
                    "dolzinaOkvirja": 3.6,

                    "faktorSencil": 0.3,

                    "stranskoSencenje": {
                        "zgorajDolzina": 0.2,
                        "zgorajRazdalja": 0,
                        "levoDolzina": 0.2,
                        "levoRazdalja": 0,
                        "desnoDolzina": 0.2,
                        "desnoRazdalja": 0
                    }
                },
                {
                    "id": "O4",
                    "idKonstrukcije": "O1",
                    "stevilo": 2,
                    
                    "povrsina": 1,
                    "naklon": 90,
                    "orientacija": "S",
                    
                    "visinaStekla": 0.9,
                    "sirinaStekla": 0.9,

                    "delezOkvirja": 0.19,
                    "dolzinaOkvirja": 3.6,

                    "faktorSencil": 0.3,

                    "stranskoSencenje": {
                        "zgorajDolzina": 0.2,
                        "zgorajRazdalja": 0,
                        "levoDolzina": 0.2,
                        "levoRazdalja": 0,
                        "desnoDolzina": 0.2,
                        "desnoRazdalja": 0
                    }
                }
            ]
        }
    }
]
